//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EurekaBank_Client.wsmonster {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsmonster.SWeurekabankSoap")]
    public interface SWeurekabankSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerMovimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet traerMovimiento(string num_cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerMovimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> traerMovimientoAsync(string num_cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regDeposito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet regDeposito(string num_cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> regDepositoAsync(string num_cuenta, double importe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWeurekabankSoapChannel : WS_EurekaBank_Client.wsmonster.SWeurekabankSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWeurekabankSoapClient : System.ServiceModel.ClientBase<WS_EurekaBank_Client.wsmonster.SWeurekabankSoap>, WS_EurekaBank_Client.wsmonster.SWeurekabankSoap {
        
        public SWeurekabankSoapClient() {
        }
        
        public SWeurekabankSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWeurekabankSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWeurekabankSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWeurekabankSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet traerMovimiento(string num_cuenta) {
            return base.Channel.traerMovimiento(num_cuenta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> traerMovimientoAsync(string num_cuenta) {
            return base.Channel.traerMovimientoAsync(num_cuenta);
        }
        
        public System.Data.DataSet regDeposito(string num_cuenta, double importe) {
            return base.Channel.regDeposito(num_cuenta, importe);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> regDepositoAsync(string num_cuenta, double importe) {
            return base.Channel.regDepositoAsync(num_cuenta, importe);
        }
    }
}
